IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA = 'stg' 
      AND TABLE_NAME = 'Stations'
)
BEGIN
    CREATE TABLE [stg].[Stations] (
    [id] INT NULL,
    [stationName] NVARCHAR(255) NULL,
    [fuelTypeCode] NVARCHAR(255) NULL,
    [ownerTypeCode] NVARCHAR(255) NULL,
    [country] NVARCHAR(255) NULL,
    [state] NVARCHAR(255) NULL,
    [city] NVARCHAR(255) NULL,
    [streetAddress] NVARCHAR(255) NULL,
    [zip] INT NULL,
    [openDate] DATETIMEOFFSET NULL,
    [updatedAt] DATETIMEOFFSET NULL,
    [accessCode] NVARCHAR(255) NULL,
    [accessDaysTime] NVARCHAR(255) NULL,
    [accessDetailCode] NVARCHAR(255) NULL,
    [cardsAccepted] NVARCHAR(255) NULL,
    [dateLastConfirmed] DATETIMEOFFSET NULL,
    [expectedDate] FLOAT NULL,
    [groupsWithAccessCode] NVARCHAR(255) NULL,
    [maximumVehicleClass] NVARCHAR(255) NULL,
    [restrictedAccess] BIT NULL,
    [statusCode] NVARCHAR(255) NULL,
    [facilityType] NVARCHAR(255) NULL,
    [stationPhone] NVARCHAR(255) NULL,
    [geocodeStatus] NVARCHAR(255) NULL,
    [latitude] FLOAT NULL,
    [longitude] FLOAT NULL,
    [intersectionDirections] NVARCHAR(255) NULL,
    [plus4] FLOAT NULL,
    [bdBlends] FLOAT NULL,
    [cngDispenserNum] FLOAT NULL,
    [cngFillTypeCode] FLOAT NULL,
    [cngHasRng] FLOAT NULL,
    [cngPsi] FLOAT NULL,
    [cngRenewableSource] FLOAT NULL,
    [cngTotalCompression] FLOAT NULL,
    [cngTotalStorage] FLOAT NULL,
    [cngVehicleClass] FLOAT NULL,
    [e85BlenderPump] FLOAT NULL,
    [evDcFastNum] FLOAT NULL,
    [evLevel1EvseNum] FLOAT NULL,
    [evLevel2EvseNum] FLOAT NULL,
    [evNetwork] NVARCHAR(255) NULL,
    [evNetworkWeb] FLOAT NULL,
    [evOtherEvse] NVARCHAR(255) NULL,
    [evPricing] NVARCHAR(255) NULL,
    [evRenewableSource] NVARCHAR(255) NULL,
    [evWorkplaceCharging] BIT NULL,
    [hyIsRetail] BIT NULL,
    [hyStatusLink] NVARCHAR(255) NULL,
    [lngHasRng] BIT NULL,
    [lngRenewableSource] NVARCHAR(255) NULL,
    [lngVehicleClass] NVARCHAR(255) NULL,
    [lpgPrimary] FLOAT NULL,
    [ngFillTypeCode] FLOAT NULL,
    [ngPsi] FLOAT NULL,
    [ngVehicleClass] NVARCHAR(255) NULL,
    [rdBlendedWithBiodiesel] FLOAT NULL,
    [rdBlends] FLOAT NULL,
    [rdBlendsFr] FLOAT NULL,
    [rdMaxBiodieselLevel] FLOAT NULL,
    [npsUnitName] FLOAT NULL,
    [accessDaysTimeFr] FLOAT NULL,
    [intersectionDirectionsFr] FLOAT NULL,
    [bdBlendsFr] FLOAT NULL,
    [groupsWithAccessCodeFr] NVARCHAR(255) NULL,
    [evPricingFr] FLOAT NULL,
    [restricted_access_bool] BIT NULL,
    [ev_workplace_charging_bool] BIT NULL,
    [hy_is_retail_bool] BIT NULL,
    [lng_has_rng_bool] BIT NULL,
    [InsertedAt] DATETIME NOT NULL DEFAULT GETDATE()
    );
END;