IF NOT EXISTS (
    SELECT 1 
    FROM INFORMATION_SCHEMA.TABLES 
    WHERE TABLE_SCHEMA = 'stg' 
      AND TABLE_NAME = 'FuelEconomy'
)
BEGIN
    CREATE TABLE [stg].[FuelEconomy] (
    [vehicleId] INT NULL,
    [atvType] NVARCHAR(255) NULL,
    [barrels08] FLOAT NULL,
    [barrelsA08] FLOAT NULL,
    [battery] NVARCHAR(255) NULL,
    [c240Dscr] FLOAT NULL,
    [c240bDscr] FLOAT NULL,
    [charge120] FLOAT NULL,
    [charge240] FLOAT NULL,
    [charge240b] FLOAT NULL,
    [city08] INT NULL,
    [city08U] FLOAT NULL,
    [cityA08] INT NULL,
    [cityA08U] FLOAT NULL,
    [cityCD] FLOAT NULL,
    [cityE] FLOAT NULL,
    [cityMpk] INT NULL,
    [cityUF] FLOAT NULL,
    [cityUmpk] FLOAT NULL,
    [co2] INT NULL,
    [co2A] INT NULL,
    [co2TailpipeAGpm] FLOAT NULL,
    [co2TailpipeGpm] FLOAT NULL,
    [comb08] INT NULL,
    [comb08U] FLOAT NULL,
    [combA08] INT NULL,
    [combA08U] FLOAT NULL,
    [combE] FLOAT NULL,
    [combMpk] INT NULL,
    [combUmpk] FLOAT NULL,
    [combinedCD] FLOAT NULL,
    [combinedUF] FLOAT NULL,
    [createdOn] DATETIMEOFFSET NULL,
    [cylDeact] NVARCHAR(255) NULL,
    [cylDeactYesNo] NVARCHAR(255) NULL,
    [cylinders] FLOAT NULL,
    [displ] FLOAT NULL,
    [drive] NVARCHAR(255) NULL,
    [engId] INT NULL,
    [engDscr] NVARCHAR(255) NULL,
    [evMotor] NVARCHAR(255) NULL,
    [feScore] INT NULL,
    [fuelCost08] INT NULL,
    [fuelCostA08] INT NULL,
    [fuelType] NVARCHAR(255) NULL,
    [fuelType1] NVARCHAR(255) NULL,
    [fuelType2] NVARCHAR(255) NULL,
    [ghgScore] INT NULL,
    [ghgScoreA] INT NULL,
    [guzzler] NVARCHAR(255) NULL,
    [highway08] INT NULL,
    [highway08U] FLOAT NULL,
    [highwayA08] INT NULL,
    [highwayA08U] FLOAT NULL,
    [highwayCD] FLOAT NULL,
    [highwayE] FLOAT NULL,
    [highwayMpk] INT NULL,
    [highwayUF] FLOAT NULL,
    [highwayUmpk] FLOAT NULL,
    [hlv] INT NULL,
    [hpv] INT NULL,
    [id] INT NULL,
    [lv2] INT NULL,
    [lv4] INT NULL,
    [make] NVARCHAR(255) NULL,
    [mfrCode] NVARCHAR(255) NULL,
    [model] NVARCHAR(255) NULL,
    [modifiedOn] DATETIMEOFFSET NULL,
    [mpgData] NVARCHAR(255) NULL,
    [mpgRevised] BIT NULL,
    [phevBlended] BIT NULL,
    [phevCity] INT NULL,
    [phevComb] INT NULL,
    [phevHwy] INT NULL,
    [pv2] INT NULL,
    [pv4] INT NULL,
    [range] INT NULL,
    [rangeA] NVARCHAR(255) NULL,
    [rangeCity] FLOAT NULL,
    [rangeCityA] FLOAT NULL,
    [rangeHwy] FLOAT NULL,
    [rangeHwyA] FLOAT NULL,
    [startStop] NVARCHAR(255) NULL,
    [transDscr] FLOAT NULL,
    [trany] NVARCHAR(255) NULL,
    [uCity] FLOAT NULL,
    [uCityA] FLOAT NULL,
    [uHighway] FLOAT NULL,
    [uHighwayA] FLOAT NULL,
    [vClass] NVARCHAR(255) NULL,
    [year] INT NULL,
    [youSaveSpend] INT NULL,
    [baseModel] NVARCHAR(255) NULL,
    [sCharger] NVARCHAR(255) NULL,
    [tCharger] NVARCHAR(255) NULL,
    [cylDeact_bool] BIT NULL,
    [cylDeactYesNo_bool] BIT NULL,
    [mpgData_bool] BIT NULL,
    [mpgRevised_bool] BIT NULL,
    [phevBlended_bool] BIT NULL,
    [startStop_bool] BIT NULL,
    [InsertedAt] DATETIME NOT NULL DEFAULT GETDATE()
    );
END;